login_base:
    - action: goto
      value: "/#/login"
    - action: click
      selector: "账号密码登录tab"
    - action: fill
      selector: "账号输入框"
      value: ${user_name}
    - action: fill
      selector: "密码输入框"
      value: ${password}
    - action: click
      selector: "登录按钮"
login:
    - use_module: login_base
      params:
          user_name: ${mobile}
          password: ${pwd}